quarkus.artemis.password=xx
quarkus.artemis.username=xx
quarkus.artemis.url=tcp://xxxx:61616
#
quarkus.log.category.uppercaseTransformation.level=INFO
quarkus.log.category.extractBodyTransformation.level=INFO
quarkus.log.category.wrapbodyTransformation.level=INFO
