%dev.quarkus.artemis.password=artemis
%dev.quarkus.artemis.username=artemis
%dev.quarkus.artemis.url=tcp://oravm05:61616

## replace with env var like this
## export CAMEL_ROUTE_TEMPLATE_0__INQUEUE=quarkin10

%dev.camel.route-template[0].template-id=wrapbodyTransformation
%dev.camel.route-template[0].inqueue=quarkin1
%dev.camel.route-template[0].outqueue=quarkout1
%dev.camel.route-template[0].maxConsumers=10



%dev.quarkus.log.category.uppercaseTransformation.level=DEBUG
%dev.quarkus.log.category.extractBodyTransformation.level=DEBUG
%dev.quarkus.log.category.wrapbodyTransformation.level=DEBUG

