quarkus.artemis.password=artemis
quarkus.artemis.username=artemis
quarkus.artemis.url=tcp://oravm05:61616

## replace with env var like this
## export CAMEL_ROUTE_TEMPLATE_0__INQUEUE=quarkin10

camel.route-template[0].template-id=wrapbodyTransformation
camel.route-template[0].inqueue=quarkin1
camel.route-template[0].outqueue=quarkout1
camel.route-template[0].maxConsumers=10

quarkus.log.category.uppercaseTransformation.level=INFO
quarkus.log.category.extractBodyTransformation.level=INFO
quarkus.log.category.wrapbodyTransformation.level=INFO

